language: python
python:
  - "3.6"

before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dinghy-ping .
      - docker images
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/dinghy-ping:$TRAVIS_BUILD_NUMBER

    - stage: build docker image latest and git tag version it
      if: branch = master
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dinghy-ping .
      - docker images
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping:$TRAVIS_PULL_REQUEST
      - docker push $DOCKER_USERNAME/dinghy-ping:$TRAVIS_PULL_REQUEST
      if: branch = master and tag IS present
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dinghy-ping .
      - docker images
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping:$TRAVIS_TAG
      - docker push $DOCKER_USERNAME/dinghy-ping:$TRAVIS_TAG
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping
      - docker push $DOCKER_USERNAME/dinghy-ping
