language: python
python:
  - "3.6"

before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - pip install pipenv
  - pipenv install --dev

jobs:
  include:
    - stage: run tests
      script: pytest tests/ --disable-pytest-warnings 
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dinghy-ping .
      - docker images
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping:build_$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/dinghy-ping:build_$TRAVIS_BUILD_NUMBER
    - stage: build docker image and tag with pull request number (pr_PULL_REQUEST)
      if: branch = master
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dinghy-ping .
      - docker images
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping:pr_$TRAVIS_PULL_REQUEST
      - docker push $DOCKER_USERNAME/dinghy-ping:pr_$TRAVIS_PULL_REQUEST
    - stage: build docker image latest and git tag version it
      if: tag IS present
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dinghy-ping .
      - docker images
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping:$TRAVIS_TAG
      - docker push $DOCKER_USERNAME/dinghy-ping:$TRAVIS_TAG
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping
      - docker push $DOCKER_USERNAME/dinghy-ping
