language: python
python:
  - "3.6"

before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - pip install pipenv
  - pipenv install

jobs:
  include:
    - stage: build docker image
      if: branch = master
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dinghy-ping .
      - docker images
      - docker tag dinghy-ping $DOCKER_USERNAME/dinghy-ping
      - docker push $DOCKER_USERNAME/dinghy-ping
